name: Compress Images on Push to main branch
on:
  push:
    branches:
      - master
    # paths:
    #   - '**.jpg'
    #   - '**.jpeg'
    #   - '**.png'
    #   - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with :
            fetch-depth: 0
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Compress images
