name: Compress Images on Push to main branch
on:
  push:
    branches:
      - master
    # paths:
    #   - '**.jpg'
    #   - '**.jpeg'
    #   - '**.png'
    #   - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with :
            fetch-depth: 0
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        run: |
            git config --global user.name "COMMIT_AUTHOR"
            git config --global user.email "username@users.noreply.github.com"
            git add -A
            git commit -m "COMMIT_MESSAGE"
            git push
